// Demo product catalog used to seed MongoDB. Images point to Unsplash source
// placeholders — swap for real product photography in production.
const products = [
  {
    name: 'Aurora Wireless Headphones',
    slug: 'aurora-wireless-headphones',
    description:
      'Immerse yourself in studio-quality sound with active noise cancellation, 40-hour battery life, and a featherlight titanium frame built for all-day comfort.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    images: [],
    category: 'Electronics',
    price: 249.99,
    originalPrice: 299.99,
    countInStock: 25,
    rating: 4.7,
    numReviews: 128,
    featured: true,
    tags: ['audio', 'wireless', 'headphones'],
  },
  {
    name: 'Nebula Smartwatch Pro',
    slug: 'nebula-smartwatch-pro',
    description:
      'A precision-engineered smartwatch with AMOLED display, real-time health tracking, GPS, and 7-day battery life — your co-pilot for work, workouts, and everything between.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
    category: 'Electronics',
    price: 329.0,
    originalPrice: 399.0,
    countInStock: 18,
    rating: 4.6,
    numReviews: 94,
    featured: true,
    tags: ['wearable', 'smartwatch', 'fitness'],
  },
  {
    name: 'Quantum Mechanical Keyboard',
    slug: 'quantum-mechanical-keyboard',
    description:
      'Hot-swappable mechanical switches, per-key RGB, and a CNC aluminum chassis. Designed for coders, creators, and competitive gamers who refuse to compromise.',
    image: 'https://images.unsplash.com/photo-1595225476474-63038da0e2ac?w=800',
    category: 'Gaming',
    price: 159.99,
    originalPrice: 189.99,
    countInStock: 40,
    rating: 4.8,
    numReviews: 210,
    featured: true,
    tags: ['keyboard', 'gaming', 'mechanical'],
  },
  {
    name: 'Halo Ultra-Slim Laptop Sleeve',
    slug: 'halo-ultra-slim-laptop-sleeve',
    description:
      'Water-resistant, shock-absorbing sleeve crafted from recycled neoprene. Slim enough to fit in your favorite bag, tough enough to protect what matters.',
    image: 'https://images.unsplash.com/photo-1512314889357-e157c22f938d?w=800',
    category: 'Accessories',
    price: 39.99,
    originalPrice: 0,
    countInStock: 60,
    rating: 4.4,
    numReviews: 67,
    featured: false,
    tags: ['laptop', 'sleeve', 'accessories'],
  },
  {
    name: 'Zenith Running Sneakers',
    slug: 'zenith-running-sneakers',
    description:
      'Engineered mesh upper, responsive foam midsole, and a carbon plate for explosive energy return — built for runners chasing new personal bests.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    category: 'Sports',
    price: 129.99,
    originalPrice: 159.99,
    countInStock: 35,
    rating: 4.5,
    numReviews: 156,
    featured: true,
    tags: ['shoes', 'running', 'sports'],
  },
  {
    name: 'Drift Oversized Hoodie',
    slug: 'drift-oversized-hoodie',
    description:
      'Heavyweight brushed fleece with a relaxed, oversized cut. A modern streetwear staple that pairs effortlessly with everything in your rotation.',
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
    category: 'Fashion',
    price: 74.99,
    originalPrice: 89.99,
    countInStock: 50,
    rating: 4.3,
    numReviews: 88,
    featured: false,
    tags: ['hoodie', 'streetwear', 'fashion'],
  },
  {
    name: 'Lumen Smart Desk Lamp',
    slug: 'lumen-smart-desk-lamp',
    description:
      'App-controlled color temperature, wireless charging base, and adaptive brightness that follows the sun. Illuminate your workspace, intelligently.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
    category: 'Home & Living',
    price: 89.99,
    originalPrice: 0,
    countInStock: 30,
    rating: 4.6,
    numReviews: 73,
    featured: true,
    tags: ['lamp', 'smart-home', 'lighting'],
  },
  {
    name: 'Velvet Matte Lipstick Set',
    slug: 'velvet-matte-lipstick-set',
    description:
      'A curated set of six long-wear matte lipsticks in universally flattering shades, formulated with nourishing vitamin E and zero animal testing.',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800',
    category: 'Beauty',
    price: 45.0,
    originalPrice: 60.0,
    countInStock: 45,
    rating: 4.5,
    numReviews: 112,
    featured: false,
    tags: ['makeup', 'lipstick', 'beauty'],
  },
  {
    name: 'Pulse Gaming Mouse',
    slug: 'pulse-gaming-mouse',
    description:
      '26,000 DPI optical sensor, ultra-lightweight honeycomb shell, and 70-hour battery life. Precision built for competitive esports.',
    image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=800',
    category: 'Gaming',
    price: 79.99,
    originalPrice: 99.99,
    countInStock: 55,
    rating: 4.7,
    numReviews: 189,
    featured: false,
    tags: ['mouse', 'gaming', 'esports'],
  },
  {
    name: 'Terra Ceramic Cookware Set',
    slug: 'terra-ceramic-cookware-set',
    description:
      'A 10-piece non-toxic ceramic-coated cookware set that heats evenly and cleans effortlessly. Elevate weeknight dinners into something special.',
    image: 'https://images.unsplash.com/photo-1584990347449-a2d4c1f14ded?w=800',
    category: 'Home & Living',
    price: 199.99,
    originalPrice: 259.99,
    countInStock: 20,
    rating: 4.8,
    numReviews: 64,
    featured: true,
    tags: ['cookware', 'kitchen', 'home'],
  },
  {
    name: 'Orbit Backpack 2.0',
    slug: 'orbit-backpack-2',
    description:
      'A weatherproof 25L daypack with a padded 16" laptop compartment, hidden anti-theft pocket, and USB charging port for life on the move.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
    category: 'Accessories',
    price: 89.99,
    originalPrice: 109.99,
    countInStock: 42,
    rating: 4.6,
    numReviews: 97,
    featured: false,
    tags: ['backpack', 'travel', 'accessories'],
  },
  {
    name: 'Flux Resistance Band Kit',
    slug: 'flux-resistance-band-kit',
    description:
      'Five progressive resistance bands, a door anchor, and a carry bag — everything you need for a full-body workout, anywhere in the world.',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800',
    category: 'Sports',
    price: 29.99,
    originalPrice: 0,
    countInStock: 70,
    rating: 4.2,
    numReviews: 51,
    featured: false,
    tags: ['fitness', 'home-gym', 'sports'],
  },
];

export default products;
